/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import dashboardMain.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Dipanshu
 */
public class NewLogin extends javax.swing.JFrame {

    /**
     * Creates new form NewLogin
     */
    StringBuffer pwd;
    ButtonGroup btngrp;
    public NewLogin() {
        initComponents();
        pwd = new StringBuffer("");//store password
        btngrp = new ButtonGroup();
        btngrp.add(otherGender);
        btngrp.add(maleGender);
        btngrp.add(femaleGender);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        detailContiner = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        contentContainer = new javax.swing.JPanel();
        loginContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JTextField();
        loginBtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        goToRegister = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        showPwd = new javax.swing.JLabel();
        registerContainer = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        registerBtn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cancelBtnRegister = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        goToLogin = new javax.swing.JButton();
        lastName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        newPassword = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        femaleGender = new javax.swing.JRadioButton();
        maleGender = new javax.swing.JRadioButton();
        otherGender = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        detailContiner.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/main.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 255));
        jLabel9.setText("Catering Management System");

        javax.swing.GroupLayout detailContinerLayout = new javax.swing.GroupLayout(detailContiner);
        detailContiner.setLayout(detailContinerLayout);
        detailContinerLayout.setHorizontalGroup(
            detailContinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailContinerLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(detailContinerLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detailContinerLayout.setVerticalGroup(
            detailContinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailContinerLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        getContentPane().add(detailContiner);

        contentContainer.setBackground(new java.awt.Color(255, 255, 255));
        contentContainer.setLayout(new java.awt.CardLayout());

        loginContainer.setBackground(new java.awt.Color(0, 200, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/catering.png"))); // NOI18N

        usernameTxt.setBackground(new java.awt.Color(0, 200, 255));
        usernameTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        usernameTxt.setForeground(new java.awt.Color(255, 255, 255));
        usernameTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        usernameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTxtFocusLost(evt);
            }
        });
        usernameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtActionPerformed(evt);
            }
        });

        passwordTxt.setBackground(new java.awt.Color(0, 200, 255));
        passwordTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(255, 255, 255));
        passwordTxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        passwordTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTxtFocusLost(evt);
            }
        });
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        passwordTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordTxtKeyReleased(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(255, 255, 255));
        loginBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
        });
        loginBtn.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 200, 255));
        jLabel5.setText("Login");
        loginBtn.add(jLabel5, new java.awt.GridBagConstraints());

        cancelBtn.setBackground(new java.awt.Color(0, 200, 255));
        cancelBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelBtnMouseExited(evt);
            }
        });
        cancelBtn.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cancel");
        cancelBtn.add(jLabel7, new java.awt.GridBagConstraints());

        goToRegister.setBackground(new java.awt.Color(204, 255, 255));
        goToRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        goToRegister.setForeground(new java.awt.Color(255, 255, 255));
        goToRegister.setText("Don't have an account?");
        goToRegister.setBorder(null);
        goToRegister.setBorderPainted(false);
        goToRegister.setContentAreaFilled(false);
        goToRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goToRegister.setDefaultCapable(false);
        goToRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                goToRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                goToRegisterMouseExited(evt);
            }
        });
        goToRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToRegisterActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CMS");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password*");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username*");

        showPwd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showPwd.setForeground(new java.awt.Color(255, 255, 255));
        showPwd.setText("Hover to Show");
        showPwd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showPwdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showPwdMouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginContainerLayout = new javax.swing.GroupLayout(loginContainer);
        loginContainer.setLayout(loginContainerLayout);
        loginContainerLayout.setHorizontalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContainerLayout.createSequentialGroup()
                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginContainerLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(goToRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginContainerLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginContainerLayout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginContainerLayout.createSequentialGroup()
                            .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(194, 194, 194))
                        .addGroup(loginContainerLayout.createSequentialGroup()
                            .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(showPwd)
                                .addGroup(loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addContainerGap()))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(327, 327, 327))
        );
        loginContainerLayout.setVerticalGroup(
            loginContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginContainerLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPwd)
                .addGap(20, 20, 20)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goToRegister)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        contentContainer.add(loginContainer, "card2");

        registerContainer.setBackground(new java.awt.Color(0, 200, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Register");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("First Name*");

        firstName.setBackground(new java.awt.Color(0, 200, 255));
        firstName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        firstName.setForeground(new java.awt.Color(255, 255, 255));
        firstName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        firstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstNameFocusGained(evt);
            }
        });
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });

        registerBtn.setBackground(new java.awt.Color(255, 255, 255));
        registerBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerBtnMouseExited(evt);
            }
        });
        registerBtn.setLayout(new java.awt.GridBagLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 200, 255));
        jLabel11.setText("Register");
        registerBtn.add(jLabel11, new java.awt.GridBagConstraints());

        cancelBtnRegister.setBackground(new java.awt.Color(0, 200, 255));
        cancelBtnRegister.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        cancelBtnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelBtnRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelBtnRegisterMouseExited(evt);
            }
        });
        cancelBtnRegister.setLayout(new java.awt.GridBagLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cancel");
        cancelBtnRegister.add(jLabel12, new java.awt.GridBagConstraints());

        goToLogin.setBackground(new java.awt.Color(204, 255, 255));
        goToLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        goToLogin.setForeground(new java.awt.Color(255, 255, 255));
        goToLogin.setText("Have an account?");
        goToLogin.setBorder(null);
        goToLogin.setBorderPainted(false);
        goToLogin.setContentAreaFilled(false);
        goToLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goToLogin.setDefaultCapable(false);
        goToLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                goToLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                goToLoginMouseExited(evt);
            }
        });
        goToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToLoginActionPerformed(evt);
            }
        });

        lastName.setBackground(new java.awt.Color(0, 200, 255));
        lastName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lastName.setForeground(new java.awt.Color(255, 255, 255));
        lastName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        lastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameFocusGained(evt);
            }
        });
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Last Name*");

        contact.setBackground(new java.awt.Color(0, 200, 255));
        contact.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 255, 255));
        contact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        contact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactFocusGained(evt);
            }
        });
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Contact*");

        email.setBackground(new java.awt.Color(0, 200, 255));
        email.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Email*");

        address.setBackground(new java.awt.Color(0, 200, 255));
        address.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFocusGained(evt);
            }
        });
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Address*");

        newPassword.setBackground(new java.awt.Color(0, 200, 255));
        newPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        newPassword.setForeground(new java.awt.Color(255, 255, 255));
        newPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        newPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newPasswordFocusGained(evt);
            }
        });
        newPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPasswordActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("New Password*");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Gender*");

        femaleGender.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        femaleGender.setForeground(new java.awt.Color(255, 255, 255));
        femaleGender.setText("Female");

        maleGender.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        maleGender.setForeground(new java.awt.Color(255, 255, 255));
        maleGender.setText("Male");

        otherGender.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        otherGender.setForeground(new java.awt.Color(255, 255, 255));
        otherGender.setText("Others");

        javax.swing.GroupLayout registerContainerLayout = new javax.swing.GroupLayout(registerContainer);
        registerContainer.setLayout(registerContainerLayout);
        registerContainerLayout.setHorizontalGroup(
            registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerContainerLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerContainerLayout.createSequentialGroup()
                        .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registerContainerLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(250, 250, 250)
                                .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(registerContainerLayout.createSequentialGroup()
                                        .addComponent(otherGender)
                                        .addGap(27, 27, 27)
                                        .addComponent(maleGender))
                                    .addComponent(femaleGender)))
                            .addComponent(jLabel17))
                        .addContainerGap(135, Short.MAX_VALUE))
                    .addGroup(registerContainerLayout.createSequentialGroup()
                        .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(address, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(newPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(64, 64, 64))))
            .addGroup(registerContainerLayout.createSequentialGroup()
                .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerContainerLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel8))
                    .addGroup(registerContainerLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelBtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(goToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );
        registerContainerLayout.setVerticalGroup(
            registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerContainerLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerContainerLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, 0)
                        .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerContainerLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, 0)
                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerContainerLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, 0)
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerContainerLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, 0)
                        .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(registerContainerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(otherGender)
                            .addComponent(maleGender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(femaleGender))
                    .addGroup(registerContainerLayout.createSequentialGroup()
                        .addComponent(newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel16)))
                .addGap(0, 0, 0)
                .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelBtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(goToLogin)
                .addGap(93, 93, 93))
        );

        contentContainer.add(registerContainer, "card2");

        getContentPane().add(contentContainer);

        setSize(new java.awt.Dimension(1390, 760));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTxtActionPerformed

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    /*to update query
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/catering_management","root","");
            String query = "insert into Admin values('DEEPANSHU CHAUHAN','deepshshuchauhan@gmail.com','9876543210','deepanshu@123',0);";
            Statement stmt = con.createStatement();
            int msg = stmt.executeUpdate(query);
    */
    
    
    private Connection databaseConnection(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            return DriverManager.getConnection("jdbc:mysql://localhost:3306/catering_management","root","");
        }catch(Exception e){
            JOptionPane.showMessageDialog(contentContainer, e);
            return null;
        }
    }
    
    
    
    
    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        String username = usernameTxt.getText();
        String pwd = passwordTxt.getText();
        if(username.equals("")){
            JOptionPane.showMessageDialog(contentContainer, "Please Enter username.");
        }else if(pwd.equals("")){
            JOptionPane.showMessageDialog(contentContainer, "Please Enter password.");
        }else{
            try{
                Connection con = databaseConnection();
                String query = "select pwd from Admin where email = '"+username+"';";
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(query);
                if(rs.next()){
                    if(rs.getString("pwd").equals(pwd)){
                           DashboardAdmin dashboard = new DashboardAdmin(username);
                           dashboard.setVisible(true);
                           this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(contentContainer, "Please Enter a Valid Password.");
                    }
                }else{
                    query = "select pwd from Staffs where email = '"+username+"';";
                    rs = stmt.executeQuery(query);
                    if(rs.next()){
                        if(rs.getString("pwd").equals(pwd)){
                             DashboardStaff dashboard = new DashboardStaff(username);
                             dashboard.setVisible(true);
                             this.dispose();
                        }else{
                             JOptionPane.showMessageDialog(contentContainer, "Please Enter a Valid Password");
                        }
                    }else{
                        JOptionPane.showMessageDialog(contentContainer, "You Don't have an account.");
                    }
                }
                con.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(contentContainer, e);
                //con.close();
            }
        }

    }//GEN-LAST:event_loginBtnMouseClicked

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
        loginBtn.setBackground(new Color(250,250,250));
    }//GEN-LAST:event_loginBtnMouseEntered

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
        loginBtn.setBackground(Color.white);
    }//GEN-LAST:event_loginBtnMouseExited

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseClicked
        dispose();
    }//GEN-LAST:event_cancelBtnMouseClicked

    private void cancelBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseEntered
        cancelBtn.setBackground(Color.red);
    }//GEN-LAST:event_cancelBtnMouseEntered

    private void cancelBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnMouseExited
        cancelBtn.setBackground(new Color(0,200,255));
    }//GEN-LAST:event_cancelBtnMouseExited

    private void goToRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToRegisterMouseEntered
        goToRegister.setForeground(Color.white);
    }//GEN-LAST:event_goToRegisterMouseEntered

    private void goToRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToRegisterMouseExited
        goToRegister.setForeground(new Color(240,240,240));
    }//GEN-LAST:event_goToRegisterMouseExited

    private void goToRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToRegisterActionPerformed
       contentContainer.removeAll();
       contentContainer.add(registerContainer);
       contentContainer.repaint();
       contentContainer.revalidate();
    }//GEN-LAST:event_goToRegisterActionPerformed

    private void usernameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTxtFocusGained
        
    }//GEN-LAST:event_usernameTxtFocusGained

    private void passwordTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusGained
      
    }//GEN-LAST:event_passwordTxtFocusGained

    private void firstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstNameFocusGained
       
    }//GEN-LAST:event_firstNameFocusGained

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        
    }//GEN-LAST:event_firstNameActionPerformed

    private void cancelBtnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnRegisterMouseClicked
        dispose();
    }//GEN-LAST:event_cancelBtnRegisterMouseClicked

    private void cancelBtnRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnRegisterMouseEntered
        cancelBtnRegister.setBackground(Color.red);
    }//GEN-LAST:event_cancelBtnRegisterMouseEntered

    private void cancelBtnRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelBtnRegisterMouseExited
        cancelBtnRegister.setBackground(new Color(0,200,255));
    }//GEN-LAST:event_cancelBtnRegisterMouseExited

    private void goToLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToLoginMouseEntered
        goToLogin.setForeground(Color.white);
    }//GEN-LAST:event_goToLoginMouseEntered

    private void goToLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToLoginMouseExited
        goToLogin.setForeground(new Color(240,240,240));
    }//GEN-LAST:event_goToLoginMouseExited

    private void goToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToLoginActionPerformed
       contentContainer.removeAll();
       contentContainer.add(loginContainer);
       contentContainer.repaint();
       contentContainer.revalidate();
    }//GEN-LAST:event_goToLoginActionPerformed

    private void lastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameFocusGained
        
    }//GEN-LAST:event_lastNameFocusGained

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void contactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactFocusGained
        
    }//GEN-LAST:event_contactFocusGained

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
       
    }//GEN-LAST:event_emailFocusGained

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void newPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newPasswordFocusGained
 
    }//GEN-LAST:event_newPasswordFocusGained

    private void newPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPasswordActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        
    }//GEN-LAST:event_addressActionPerformed

    private void addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusGained

    }//GEN-LAST:event_addressFocusGained

    private void registerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseExited
        registerBtn.setBackground(Color.white);
    }//GEN-LAST:event_registerBtnMouseExited

    private void registerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseEntered
        registerBtn.setBackground(new Color(250,250,250));
    }//GEN-LAST:event_registerBtnMouseEntered

    private void registerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseClicked
        String f,l,e,p,g,a,c;
                f= firstName.getText();
                l = lastName.getText();
                e = email.getText();
                c = contact.getText();
                p = newPassword.getText();
                a = address.getText();
                if(otherGender.isSelected())
                    g=otherGender.getActionCommand();
                else if(maleGender.isSelected())
                    g=maleGender.getActionCommand();
                else if(femaleGender.isSelected())
                    g=femaleGender.getActionCommand();
                else
                    g="";
                if(f.equals("")&&l.equals("")&&e.equals("")&&p.equals("")&&a.equals("")&&g.equals(""))
                    JOptionPane.showMessageDialog(contentContainer,"Please fill all Required(*) fields");
                else{
                    try{
                        Connection con = databaseConnection();
                        String query = "select * from Admin where email = '"+e+"';";
                        Statement stmt = con.createStatement();
                        ResultSet rs = stmt.executeQuery(query);
                        if(rs.next()){
                            JOptionPane.showMessageDialog(contentContainer, "You already have an account with this ID");
                        }else{
                            SimpleDateFormat ft= new SimpleDateFormat("dd-MM-yyyy");
                            String today = ft.format(new Date());
                            query = "insert into Staffs values('"+(f+" "+l).toUpperCase()+"','"+e+"','"+c+"','"+g+"','"+p+"','"+a+"','"+today+"',true);";
                            stmt = con.createStatement();
                            stmt.executeUpdate(query);
                           
                            JOptionPane.showMessageDialog(contentContainer, "Registration Successful\nPlease login to continue.");
                            firstName.setText("");
                            lastName.setText("");
                            email.setText("");
                            contact.setText("");
                            newPassword.setText("");
                            address.setText("");
                        }
                        con.close();
                    }catch(Exception ex){
                        JOptionPane.showMessageDialog(contentContainer, ex);
                        //con.close();
                    }
                }
    }//GEN-LAST:event_registerBtnMouseClicked

    private void usernameTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTxtFocusLost
        
    }//GEN-LAST:event_usernameTxtFocusLost

    private void passwordTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusLost
      
    }//GEN-LAST:event_passwordTxtFocusLost

    private void showPwdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPwdMouseEntered
        showPwd.setForeground(new Color(200,255,255));
        StringBuffer p = new StringBuffer(passwordTxt.getText());
        passwordTxt.setText(pwd.toString());
        pwd = p;
    }//GEN-LAST:event_showPwdMouseEntered

    private void showPwdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showPwdMouseExited
        showPwd.setForeground(Color.white);
        StringBuffer p = new StringBuffer(passwordTxt.getText());
        passwordTxt.setText(pwd.toString());
        pwd = p;
    }//GEN-LAST:event_showPwdMouseExited

    private void passwordTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtKeyPressed
       
    }//GEN-LAST:event_passwordTxtKeyPressed

    private void passwordTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtKeyReleased
        
    }//GEN-LAST:event_passwordTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel cancelBtn;
    private javax.swing.JPanel cancelBtnRegister;
    private javax.swing.JTextField contact;
    private javax.swing.JPanel contentContainer;
    private javax.swing.JPanel detailContiner;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton femaleGender;
    private javax.swing.JTextField firstName;
    private javax.swing.JButton goToLogin;
    private javax.swing.JButton goToRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastName;
    private javax.swing.JPanel loginBtn;
    private javax.swing.JPanel loginContainer;
    private javax.swing.JRadioButton maleGender;
    private javax.swing.JTextField newPassword;
    private javax.swing.JRadioButton otherGender;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JPanel registerBtn;
    private javax.swing.JPanel registerContainer;
    private javax.swing.JLabel showPwd;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
