/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboardMain;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Container;
import javax.swing.JPanel;

/**
 *
 * @author Trideep Shivam
 */
public class DashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdmin
     */
    CardLayout cardlayout;
    Color onEnter,onExit,onClick;
    JPanel currentClickedButton;
    public DashboardAdmin() {
        initComponents();
        cardlayout = (CardLayout) (contentContainer.getLayout());
        currentClickedButton=navDashboard;
        onEnter = new Color(0,190,250);
        onExit = new Color(0,200,255);
        onClick = new Color(50,50,50);
        navDashboard.setBackground(onClick);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        contentContainer = new javax.swing.JPanel();
        dashboardContainer = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        lblDashborad = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        serviceContainer = new javax.swing.JPanel();
        lblService = new javax.swing.JLabel();
        eventContainer = new javax.swing.JPanel();
        lblEvent = new javax.swing.JLabel();
        staffContainer = new javax.swing.JPanel();
        lblStaff = new javax.swing.JLabel();
        assetContainer = new javax.swing.JPanel();
        lblAsset = new javax.swing.JLabel();
        customerContainer = new javax.swing.JPanel();
        lblCustomer = new javax.swing.JLabel();
        aboutContainer = new javax.swing.JPanel();
        lblAbout = new javax.swing.JLabel();
        logoContainer = new javax.swing.JPanel();
        menuContainer = new javax.swing.JPanel();
        navDashboard = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        navServices = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        navStaffs = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        navAssets = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        navLogout = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        navEvent = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        navAbout = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        navCustomer = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        topNav = new javax.swing.JPanel();
        btnclose = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        contentContainer.setBackground(new java.awt.Color(0, 204, 255));
        contentContainer.setLayout(new java.awt.CardLayout());

        dashboardContainer.setBackground(new java.awt.Color(240, 255, 255));

        jPanel7.setBackground(new java.awt.Color(210, 255, 255));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 120)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 204, 255));
        jLabel37.setText("0");

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel38.setText("EVENT DONE");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel37)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jLabel38)
                .addGap(27, 27, 27))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel38)
                .addGap(33, 33, 33))
        );

        lblDashborad.setBackground(new java.awt.Color(204, 255, 255));
        lblDashborad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblDashborad.setForeground(new java.awt.Color(0, 204, 255));
        lblDashborad.setText("DASHBOARD");

        jPanel8.setBackground(new java.awt.Color(210, 255, 255));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 120)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 204, 255));
        jLabel40.setText("0");

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel41.setText("HAPPENINGS");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel40)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel41)
                .addGap(30, 30, 30))
        );

        jPanel9.setBackground(new java.awt.Color(210, 255, 255));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 120)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 204, 255));
        jLabel42.setText("0");

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel43.setText("PENDINGS");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel42)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                    .addContainerGap(146, Short.MAX_VALUE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                    .addContainerGap(154, Short.MAX_VALUE)
                    .addComponent(jLabel43)
                    .addGap(26, 26, 26)))
        );

        jPanel10.setBackground(new java.awt.Color(210, 255, 255));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 120)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 204, 255));
        jLabel44.setText("0");

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel45.setText("PRESENT STAFFS");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel44)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel11.setBackground(new java.awt.Color(210, 255, 255));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dashboardContainerLayout = new javax.swing.GroupLayout(dashboardContainer);
        dashboardContainer.setLayout(dashboardContainerLayout);
        dashboardContainerLayout.setHorizontalGroup(
            dashboardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardContainerLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(dashboardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dashboardContainerLayout.createSequentialGroup()
                        .addComponent(lblDashborad)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(dashboardContainerLayout.createSequentialGroup()
                        .addGroup(dashboardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(dashboardContainerLayout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 58, Short.MAX_VALUE)
                        .addGroup(dashboardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(61, 61, 61))))
        );
        dashboardContainerLayout.setVerticalGroup(
            dashboardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardContainerLayout.createSequentialGroup()
                .addComponent(lblDashborad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dashboardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(dashboardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );

        contentContainer.add(dashboardContainer, "card2");

        serviceContainer.setBackground(new java.awt.Color(240, 255, 255));

        lblService.setBackground(new java.awt.Color(204, 255, 255));
        lblService.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblService.setForeground(new java.awt.Color(0, 204, 255));
        lblService.setText("SERVICES");

        javax.swing.GroupLayout serviceContainerLayout = new javax.swing.GroupLayout(serviceContainer);
        serviceContainer.setLayout(serviceContainerLayout);
        serviceContainerLayout.setHorizontalGroup(
            serviceContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serviceContainerLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblService)
                .addGap(0, 921, Short.MAX_VALUE))
        );
        serviceContainerLayout.setVerticalGroup(
            serviceContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(serviceContainerLayout.createSequentialGroup()
                .addComponent(lblService, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(680, Short.MAX_VALUE))
        );

        contentContainer.add(serviceContainer, "card2");

        eventContainer.setBackground(new java.awt.Color(240, 255, 255));

        lblEvent.setBackground(new java.awt.Color(204, 255, 255));
        lblEvent.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEvent.setForeground(new java.awt.Color(0, 204, 255));
        lblEvent.setText("EVENT");

        javax.swing.GroupLayout eventContainerLayout = new javax.swing.GroupLayout(eventContainer);
        eventContainer.setLayout(eventContainerLayout);
        eventContainerLayout.setHorizontalGroup(
            eventContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventContainerLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblEvent)
                .addGap(0, 954, Short.MAX_VALUE))
        );
        eventContainerLayout.setVerticalGroup(
            eventContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventContainerLayout.createSequentialGroup()
                .addComponent(lblEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(680, Short.MAX_VALUE))
        );

        contentContainer.add(eventContainer, "card2");

        staffContainer.setBackground(new java.awt.Color(240, 255, 255));

        lblStaff.setBackground(new java.awt.Color(204, 255, 255));
        lblStaff.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblStaff.setForeground(new java.awt.Color(0, 204, 255));
        lblStaff.setText("STAFFS");

        javax.swing.GroupLayout staffContainerLayout = new javax.swing.GroupLayout(staffContainer);
        staffContainer.setLayout(staffContainerLayout);
        staffContainerLayout.setHorizontalGroup(
            staffContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffContainerLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblStaff)
                .addGap(0, 945, Short.MAX_VALUE))
        );
        staffContainerLayout.setVerticalGroup(
            staffContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffContainerLayout.createSequentialGroup()
                .addComponent(lblStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(680, Short.MAX_VALUE))
        );

        contentContainer.add(staffContainer, "card2");

        assetContainer.setBackground(new java.awt.Color(240, 255, 255));

        lblAsset.setBackground(new java.awt.Color(204, 255, 255));
        lblAsset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAsset.setForeground(new java.awt.Color(0, 204, 255));
        lblAsset.setText("ASSETS");

        javax.swing.GroupLayout assetContainerLayout = new javax.swing.GroupLayout(assetContainer);
        assetContainer.setLayout(assetContainerLayout);
        assetContainerLayout.setHorizontalGroup(
            assetContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assetContainerLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblAsset)
                .addGap(0, 944, Short.MAX_VALUE))
        );
        assetContainerLayout.setVerticalGroup(
            assetContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assetContainerLayout.createSequentialGroup()
                .addComponent(lblAsset, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(680, Short.MAX_VALUE))
        );

        contentContainer.add(assetContainer, "card2");

        customerContainer.setBackground(new java.awt.Color(240, 255, 255));

        lblCustomer.setBackground(new java.awt.Color(204, 255, 255));
        lblCustomer.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblCustomer.setForeground(new java.awt.Color(0, 204, 255));
        lblCustomer.setText("CUSTOMER");

        javax.swing.GroupLayout customerContainerLayout = new javax.swing.GroupLayout(customerContainer);
        customerContainer.setLayout(customerContainerLayout);
        customerContainerLayout.setHorizontalGroup(
            customerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerContainerLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblCustomer)
                .addGap(0, 898, Short.MAX_VALUE))
        );
        customerContainerLayout.setVerticalGroup(
            customerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerContainerLayout.createSequentialGroup()
                .addComponent(lblCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(680, Short.MAX_VALUE))
        );

        contentContainer.add(customerContainer, "card2");

        aboutContainer.setBackground(new java.awt.Color(240, 255, 255));

        lblAbout.setBackground(new java.awt.Color(204, 255, 255));
        lblAbout.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAbout.setForeground(new java.awt.Color(0, 204, 255));
        lblAbout.setText("ABOUT");

        javax.swing.GroupLayout aboutContainerLayout = new javax.swing.GroupLayout(aboutContainer);
        aboutContainer.setLayout(aboutContainerLayout);
        aboutContainerLayout.setHorizontalGroup(
            aboutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutContainerLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblAbout)
                .addGap(0, 947, Short.MAX_VALUE))
        );
        aboutContainerLayout.setVerticalGroup(
            aboutContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutContainerLayout.createSequentialGroup()
                .addComponent(lblAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(680, Short.MAX_VALUE))
        );

        contentContainer.add(aboutContainer, "card2");

        logoContainer.setBackground(new java.awt.Color(0, 205, 255));

        menuContainer.setBackground(new java.awt.Color(0, 200, 255));

        navDashboard.setBackground(new java.awt.Color(0, 200, 255));
        navDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navDashboardMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DASHBOARD");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardMain/dashboard.png"))); // NOI18N

        javax.swing.GroupLayout navDashboardLayout = new javax.swing.GroupLayout(navDashboard);
        navDashboard.setLayout(navDashboardLayout);
        navDashboardLayout.setHorizontalGroup(
            navDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        navDashboardLayout.setVerticalGroup(
            navDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navDashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(navDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navDashboardLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navDashboardLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18))))
        );

        navServices.setBackground(new java.awt.Color(0, 200, 255));
        navServices.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navServicesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navServicesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navServicesMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SERVICES");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardMain/technical-support.png"))); // NOI18N

        javax.swing.GroupLayout navServicesLayout = new javax.swing.GroupLayout(navServices);
        navServices.setLayout(navServicesLayout);
        navServicesLayout.setHorizontalGroup(
            navServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navServicesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navServicesLayout.setVerticalGroup(
            navServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navServicesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navServicesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        navStaffs.setBackground(new java.awt.Color(0, 200, 255));
        navStaffs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navStaffs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navStaffsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navStaffsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navStaffsMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("STAFFS");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardMain/id-card.png"))); // NOI18N

        javax.swing.GroupLayout navStaffsLayout = new javax.swing.GroupLayout(navStaffs);
        navStaffs.setLayout(navStaffsLayout);
        navStaffsLayout.setHorizontalGroup(
            navStaffsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navStaffsLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel11)
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navStaffsLayout.setVerticalGroup(
            navStaffsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navStaffsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(navStaffsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        navAssets.setBackground(new java.awt.Color(0, 200, 255));
        navAssets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navAssets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navAssetsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navAssetsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navAssetsMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ASSETS");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardMain/big-data.png"))); // NOI18N

        javax.swing.GroupLayout navAssetsLayout = new javax.swing.GroupLayout(navAssets);
        navAssets.setLayout(navAssetsLayout);
        navAssetsLayout.setHorizontalGroup(
            navAssetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navAssetsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navAssetsLayout.setVerticalGroup(
            navAssetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navAssetsLayout.createSequentialGroup()
                .addGroup(navAssetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navAssetsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(navAssetsLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        navLogout.setBackground(new java.awt.Color(0, 200, 255));
        navLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navLogoutMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("LOGOUT");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardMain/logout.png"))); // NOI18N

        javax.swing.GroupLayout navLogoutLayout = new javax.swing.GroupLayout(navLogout);
        navLogout.setLayout(navLogoutLayout);
        navLogoutLayout.setHorizontalGroup(
            navLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(38, 38, 38)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        navLogoutLayout.setVerticalGroup(
            navLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLogoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(navLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        navEvent.setBackground(new java.awt.Color(0, 200, 255));
        navEvent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navEventMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navEventMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navEventMouseExited(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("EVENT");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardMain/event.png"))); // NOI18N

        javax.swing.GroupLayout navEventLayout = new javax.swing.GroupLayout(navEvent);
        navEvent.setLayout(navEventLayout);
        navEventLayout.setHorizontalGroup(
            navEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navEventLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addGap(37, 37, 37)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navEventLayout.setVerticalGroup(
            navEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navEventLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navEventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navEventLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        navAbout.setBackground(new java.awt.Color(0, 200, 255));
        navAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navAboutMouseExited(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("ABOUT");

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardMain/information.png"))); // NOI18N

        javax.swing.GroupLayout navAboutLayout = new javax.swing.GroupLayout(navAbout);
        navAbout.setLayout(navAboutLayout);
        navAboutLayout.setHorizontalGroup(
            navAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel35)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navAboutLayout.setVerticalGroup(
            navAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navAboutLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        navCustomer.setBackground(new java.awt.Color(0, 200, 255));
        navCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                navCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                navCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                navCustomerMouseExited(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("CUSTOMER");

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardMain/communication.png"))); // NOI18N

        javax.swing.GroupLayout navCustomerLayout = new javax.swing.GroupLayout(navCustomer);
        navCustomer.setLayout(navCustomerLayout);
        navCustomerLayout.setHorizontalGroup(
            navCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(37, 37, 37)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navCustomerLayout.setVerticalGroup(
            navCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navCustomerLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout menuContainerLayout = new javax.swing.GroupLayout(menuContainer);
        menuContainer.setLayout(menuContainerLayout);
        menuContainerLayout.setHorizontalGroup(
            menuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navAssets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(navCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(navEvent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(navServices, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(navDashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(navAbout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(navStaffs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuContainerLayout.setVerticalGroup(
            menuContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuContainerLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(navDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navServices, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navStaffs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navAssets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(navLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CMS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Catering Management System");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboardMain/icons8-catering-64.png"))); // NOI18N

        javax.swing.GroupLayout logoContainerLayout = new javax.swing.GroupLayout(logoContainer);
        logoContainer.setLayout(logoContainerLayout);
        logoContainerLayout.setHorizontalGroup(
            logoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(logoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(logoContainerLayout.createSequentialGroup()
                .addComponent(menuContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        logoContainerLayout.setVerticalGroup(
            logoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(logoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(logoContainerLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(menuContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        topNav.setBackground(new java.awt.Color(0, 205, 255));
        topNav.setForeground(new java.awt.Color(255, 255, 255));

        btnclose.setBackground(new java.awt.Color(204, 255, 255));
        btnclose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnclose.setForeground(new java.awt.Color(255, 255, 255));
        btnclose.setText("Exit");
        btnclose.setBorder(null);
        btnclose.setBorderPainted(false);
        btnclose.setContentAreaFilled(false);
        btnclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclose.setDefaultCapable(false);
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncloseMouseExited(evt);
            }
        });
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Hi, User");

        javax.swing.GroupLayout topNavLayout = new javax.swing.GroupLayout(topNav);
        topNav.setLayout(topNavLayout);
        topNavLayout.setHorizontalGroup(
            topNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topNavLayout.createSequentialGroup()
                .addGap(0, 946, Short.MAX_VALUE)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        topNavLayout.setVerticalGroup(
            topNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topNavLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(topNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(btnclose))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(contentContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(topNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(logoContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("dashboard");

        setSize(new java.awt.Dimension(1394, 761));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseEntered
        btnclose.setForeground(Color.red);
    }//GEN-LAST:event_btncloseMouseEntered

    private void btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseExited
        btnclose.setForeground(Color.white);
    }//GEN-LAST:event_btncloseMouseExited

    private void navEventMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navEventMouseExited
       setHoverEffect(navEvent,false);
    }//GEN-LAST:event_navEventMouseExited

    private void navEventMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navEventMouseEntered
        setHoverEffect(navEvent,true);
    }//GEN-LAST:event_navEventMouseEntered

    private void navLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLogoutMouseExited
        setHoverEffect(navLogout,false);
    }//GEN-LAST:event_navLogoutMouseExited

    private void navLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navLogoutMouseEntered
        setHoverEffect(navLogout,true);
    }//GEN-LAST:event_navLogoutMouseEntered

    private void navAssetsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAssetsMouseExited
        setHoverEffect(navAssets,false);
    }//GEN-LAST:event_navAssetsMouseExited

    private void navAssetsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAssetsMouseEntered
        setHoverEffect(navAssets,true);
    }//GEN-LAST:event_navAssetsMouseEntered

    private void navStaffsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navStaffsMouseExited
        setHoverEffect(navStaffs,false);
    }//GEN-LAST:event_navStaffsMouseExited

    private void navStaffsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navStaffsMouseEntered
        setHoverEffect(navStaffs,true);
    }//GEN-LAST:event_navStaffsMouseEntered

    private void navServicesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navServicesMouseExited
        setHoverEffect(navServices,false);
    }//GEN-LAST:event_navServicesMouseExited

    private void navServicesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navServicesMouseEntered
        setHoverEffect(navServices,true);
    }//GEN-LAST:event_navServicesMouseEntered

    private void navDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDashboardMouseExited
        setHoverEffect(navDashboard,false);
    }//GEN-LAST:event_navDashboardMouseExited

    private void navDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDashboardMouseEntered
        setHoverEffect(navDashboard,true);
    }//GEN-LAST:event_navDashboardMouseEntered

    private void navAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAboutMouseExited
       setHoverEffect(navAbout,false);
    }//GEN-LAST:event_navAboutMouseExited

    private void navAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAboutMouseEntered
        setHoverEffect(navAbout,true);
    }//GEN-LAST:event_navAboutMouseEntered

    private void navCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navCustomerMouseExited
        setHoverEffect(navCustomer,false);
    }//GEN-LAST:event_navCustomerMouseExited

    private void navCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navCustomerMouseEntered
        setHoverEffect(navCustomer,true);
    }//GEN-LAST:event_navCustomerMouseEntered

    private void navDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navDashboardMouseClicked
       panelChange(dashboardContainer,navDashboard);
    }//GEN-LAST:event_navDashboardMouseClicked

    private void navServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navServicesMouseClicked
        panelChange(serviceContainer,navServices);
    }//GEN-LAST:event_navServicesMouseClicked

    private void navEventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navEventMouseClicked
        panelChange(eventContainer,navEvent);
    }//GEN-LAST:event_navEventMouseClicked

    private void navStaffsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navStaffsMouseClicked
        panelChange(staffContainer,navStaffs);
    }//GEN-LAST:event_navStaffsMouseClicked

    private void navAssetsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAssetsMouseClicked
        panelChange(assetContainer,navAssets);
    }//GEN-LAST:event_navAssetsMouseClicked

    private void navCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navCustomerMouseClicked
        panelChange(customerContainer,navCustomer);
    }//GEN-LAST:event_navCustomerMouseClicked

    private void navAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navAboutMouseClicked
        panelChange(aboutContainer,navAbout);
    }//GEN-LAST:event_navAboutMouseClicked
    public void panelChange(Container content,JPanel btn){
       contentContainer.removeAll();
       contentContainer.add(content);
       contentContainer.repaint();
       contentContainer.revalidate();
       btn.setBackground(onClick);
       currentClickedButton.setBackground(onExit);
       currentClickedButton=btn;
    }
    public void setHoverEffect(Container c,boolean status){
        Color color = status?onEnter:onExit;//used to select color if status true then black otherwise blue
        if(!c.getBackground().equals(onClick)){
            c.setBackground(color);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutContainer;
    private javax.swing.JPanel assetContainer;
    private javax.swing.JButton btnclose;
    private javax.swing.JPanel contentContainer;
    private javax.swing.JPanel customerContainer;
    private javax.swing.JPanel dashboardContainer;
    private javax.swing.JPanel eventContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblAsset;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblDashborad;
    private javax.swing.JLabel lblEvent;
    private javax.swing.JLabel lblService;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel logoContainer;
    private javax.swing.JPanel menuContainer;
    private javax.swing.JPanel navAbout;
    private javax.swing.JPanel navAssets;
    private javax.swing.JPanel navCustomer;
    private javax.swing.JPanel navDashboard;
    private javax.swing.JPanel navEvent;
    private javax.swing.JPanel navLogout;
    private javax.swing.JPanel navServices;
    private javax.swing.JPanel navStaffs;
    private javax.swing.JPanel serviceContainer;
    private javax.swing.JPanel staffContainer;
    private javax.swing.JPanel topNav;
    // End of variables declaration//GEN-END:variables
}
